language: node_js

node_js:
  - 11.3.0

after_success:
  - npm run coverage

services:
  - mysql
  - redis

before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS tshirtshop;'
  - npm run db-setup
